.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. litecoinfinance_qt test_litecoinfinance_qt
clean: FORCE
	$(MAKE) -C .. litecoinfinance_qt_clean test_litecoinfinance_qt_clean
check: FORCE
	$(MAKE) -C .. test_litecoinfinance_qt_check
litecoinfinance-qt litecoinfinance-qt.exe: FORCE
	 $(MAKE) -C .. litecoinfinance_qt
